### récupération des pokemons
GET http://localhost:3000/pokemons HTTP/1.1

### récupération d'un pokemon
GET http://localhost:3000/pokemons/1 HTTP/1.1

### récupération des types
GET http://localhost:3000/types HTTP/1.1

### récupération des Pokemons d'un type
GET http://localhost:3000/types/10 HTTP/1.1

### récupération des teams
GET http://localhost:3000/teams HTTP/1.1

### récupération des Pokemons d'une team
GET http://localhost:3000/teams/2 HTTP/1.1

### création d'une team
POST http://localhost:3000/teams HTTP/1.1
content-type: application/json

{
    "name": "new"
}

### modification d'une team
PATCH http://localhost:3000/teams/5 HTTP/1.1
content-type: application/json

{
    "name": "niouniou"
}

### suppresion d'une team
DELETE http://localhost:3000/teams/7 HTTP/1.1

### ajout d'un Pokemon dans une team
PUT http://localhost:3000/teams/4/pokemons/10 HTTP/1.1

### suppression d'un Pokemon d'une team
DELETE http://localhost:3000/teams/2/pokemons/20 HTTP/1.1

### recherche d'un Pokemon via le moteur de recherche
GET http://localhost:3000/pokemons?searchTerm=Herbizarre HTTP/1.1

